import './cy-commands/storefront/utility-commands'
import './cy-commands/storefront/cart-commands'
import './cy-commands/glue/checkout'
import './cy-commands/backoffice/oms-transition-commands'
import './cy-commands/glue/addresses'
import './cy-commands/glue/carts'
import 'cypress-plugin-api'
import 'cypress-mochawesome-reporter/register'
